ncoding: utf-8

baseurl: /sir

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:categories/:title.html
  -
    scope:
      path: "_posts/system/os"
    values:
      categories: [system, os]
  -
    scope:
      path: "_posts/wissenschaft"
    values:
      categories: [wissenschaft]

